name: Documentation Generation

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run clean
        run: npm run clean

      - name: Run build
        run: npm run build

      - name: Generate documentation
        run: |
          npm run docs

      - name: Force-add changes
        run: git add --force docs

      - name: Commit and force push changes
        run: |
          git config --global user.name "Documentation Bot"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "Automated: Update documentation and clean temp folder"
          git push